config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :accounts

  resources :categories, param: :en_name, only: %i[index show] do
    resources :genres, param: :order_num, only: %i[show]
  end
  resources :licenses, only: :show
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :got_licenses, dependent: :destroy
  has_many :target_licenses, dependent: :destroy
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :genres
  has_many :licenses
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :licenses
  belongs_to :category
end

app/models/got_license.rb
class GotLicense < ApplicationRecord
  belongs_to :account
  belongs_to :license
end

app/models/license.rb
class License < ApplicationRecord
  has_many :got_licenses
  has_many :target_licenses

  belongs_to :category
  belongs_to :genre
end

app/models/target_license.rb
class TargetLicense < ApplicationRecord
  belongs_to :account
  belongs_to :license
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Categorizable
  before_action -> { find_category(params[:en_name]) }, only: :show

  def index
    @categories = Category.eager_load(:genres)
  end

  def show; end
end

app/controllers/concerns/categorizable.rb
module Categorizable
  extend ActiveSupport::Concern

  def find_category(en_name)
    @category = Category.find_by(en_name: en_name)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  include Categorizable
  before_action -> { find_category(params[:category_en_name]) }, only: :show

  def show
    @genre = @category.genres.find_by(order_num: params[:order_num])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  def show
    @license = License.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def features
    [
      { title: 'Recruitment', body: 'あなたを求めている企業とマッチ', icon: 'fa-solid fa-user-plus' },
      { title: 'Database', body: '1000種以上の資格情報を用意', icon: 'fa-solid fa-book-open' },
      { title: 'Chat', body: '同志と励まし会おう', icon: 'fa-solid fa-comments' },
      { title: 'Free', body: '完全無料で利用することができます！', icon: 'fa-brands fa-creative-commons-nc-jp' },
      { title: 'Security', body: '運営によるパトロール', icon: 'fa-solid fa-eye' },
      { title: 'Next...', body: 'さぁ、未来を拓こう', icon: 'fa-solid fa-door-open' }
    ]
  end

  def footers
    [
      { title: 'About', link: '#' },
      { title: 'Blog', link: '#' },
      { title: 'Team', link: '#' },
      { title: 'Pricing', link: '#' },
      { title: 'Contact', link: '#' },
      { title: 'Terms', link: '#' }
    ]
  end

  def social_apps
    [
      { title: 'Facebook', icon: 'fa-brands fa-facebook', link: '#' },
      { title: 'Instagram', icon: 'fa-brands fa-instagram', link: '#' },
      { title: 'Twitter', icon: 'fa-brands fa-twitter', link: '#' },
      { title: 'Github', icon: 'fa-brands fa-github', link: 'https://github.com/laicosjp/licenser' },
      { title: 'Dribble', icon: 'fa-brands fa-dribbble', link: '#' }
    ]
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def nav_lists
    [
      { title: 'Home', path: root_path, unique_class: (request.path == '/' ? 'text-primary' : 'hover:text-primary').to_s, active: true },
      { title: 'Categories', path: categories_path, unique_class: (request.path.include?('/categories') ? 'text-primary' : 'hover:text-primary').to_s, active: true },
      { title: 'Logout', path: destroy_account_session_path, method: 'delete', active: account_signed_in? },
      { title: 'Login', path: new_account_session_path, active: !account_signed_in? }
    ]
  end
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/views/categories/index.html.erb
<%= render "layouts/navbar" %>
<div class="container mx-auto p-4 flex flex-col gap-4">
  <h1 class="text-xl font-bold">分野の一覧</h1>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <% @categories.each do |category| %>
      <div class="border rounded-md py-2 px-4">
        <h2 class="font-bold text-primary text-lg py-1">
          <%= link_to category.name, category_path(category.en_name), class: 'link link-hover' %>
        </h2>
        <ul>
          <% category.genres.each do |genre| %>
            <li>
              <%= link_to genre.name, category_genre_path(category.en_name, genre.order_num), class: 'link link-hover' %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<%= render "layouts/navbar" %>
<div class="container mx-auto p-4 flex flex-col gap-4">
  <h1 class="text-xl font-bold"><%= @category.name %>の資格を探す</h1>
  <div class="grid grid-cols-1 md:grid-cols-4 gap-2">
    <% @category.licenses.each do |license| %>
      <%= link_to license_path(license) do %>
        <div class="border p-4 hover:bg-primary-content rounded-md">
          <p><%= license.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/genres/show.html.erb
<%= render "layouts/navbar" %>
<div class="container mx-auto p-4 flex flex-col gap-4">
  <h1 class="text-xl font-bold"><%= @genre.name %>の資格を探す</h1>
  <div class="grid grid-cols-1 md:grid-cols-4 gap-2">
    <% @genre.licenses.each do |license| %>
      <%= link_to license_path(license) do %>
        <div class="border p-4 hover:bg-primary-content rounded-md">
          <p><%= license.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<%= render "layouts/navbar" %>
<!-- Section 1 -->
<section class="px-2 py-32 bg-white md:px-0">
  <div class="container items-center max-w-6xl px-8 mx-auto xl:px-5">
    <div class="flex flex-wrap items-center sm:-mx-3">
      <div class="w-full md:w-1/2 md:px-3">
        <div
          class="w-full pb-6 space-y-6 sm:max-w-md lg:max-w-lg md:space-y-4 lg:space-y-8 xl:space-y-9 sm:pr-5 lg:pr-0 md:pb-0">
          <h1
            class="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl md:text-4xl lg:text-5xl xl:text-6xl">
            <p class="block xl:inline">全く新しい</p><br>
            <p class="block text-primary xl:inline">資格勉強のカタチ</p>
          </h1>
          <p class="mx-auto text-base text-gray-500 sm:max-w-md lg:text-xl md:max-w-3xl">大人になってから勉強の機会が減っていませんか？<br>
            社会人だからこそ資格勉強で自分の人材価値を高めよう!<br>
            ライセンサとともに。
          </p>
          <div class="relative flex flex-col sm:flex-row sm:space-x-4">
            <%= link_to new_account_registration_path, class: "flex btn btn-primary" do %>
              Subscribe here <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            <% end %>
            <%= link_to "Learn More", "#", class: "btn btn" %>
          </div>
        </div>
      </div>
      <div class="w-full md:w-1/2">
        <div class="w-full h-auto overflow-hidden rounded-md shadow-xl sm:rounded-xl">
          <%= image_tag 'classroom.jpg' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section 2 -->
<section class="py-20 bg-white">
  <div class="container max-w-6xl mx-auto">
    <h2 class="text-4xl font-bold tracking-tight text-center">Our Features</h2>
    <p class="mt-2 text-lg text-center text-gray-600">教育の概念をひっくり返せ</p>
    <div class="grid grid-cols-4 gap-8 mt-10 sm:grid-cols-8 lg:grid-cols-12 sm:px-8 xl:px-0">
      <% features.each do |feature| %>
        <div class="flex flex-col items-center justify-between col-span-4 px-8 py-12 space-y-4 overflow-hidden bg-gray-100 sm:rounded-xl">
          <div class="text-white bg-primary rounded-full w-16 h-16 flex">
            <i class="<%= feature[:icon] %> m-auto h-7"></i>
          </div>
          <h4 class="text-xl font-medium text-gray-700"><%= feature[:title] %></h4>
          <p class="text-base text-center text-gray-500"><%= feature[:body] %></p>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Section 3 -->
<section class="flex items-center justify-center py-20 bg-white min-w-screen">
  <div class="px-16 bg-white">
    <div class="container flex flex-col items-start mx-auto lg:items-center">
      <p
        class="relative flex items-start justify-start w-full text-lg font-bold tracking-wider text-primary uppercase lg:justify-center lg:items-center">
        Don't just take our word for it</p>
      <h2 class="relative flex items-start justify-start w-full max-w-3xl text-5xl font-bold lg:justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
          class="absolute right-0 hidden w-12 h-12 -mt-2 -mr-16 text-gray-200 lg:inline-block"
          viewBox="0 0 975.036 975.036">
          <path
            d="M925.036 57.197h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.399 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l36 76c11.6 24.399 40.3 35.1 65.1 24.399 66.2-28.6 122.101-64.8 167.7-108.8 55.601-53.7 93.7-114.3 114.3-181.9 20.601-67.6 30.9-159.8 30.9-276.8v-239c0-27.599-22.401-50-50-50zM106.036 913.497c65.4-28.5 121-64.699 166.9-108.6 56.1-53.7 94.4-114.1 115-181.2 20.6-67.1 30.899-159.6 30.899-277.5v-239c0-27.6-22.399-50-50-50h-304c-27.6 0-50 22.4-50 50v304c0 27.601 22.4 50 50 50h145.5c-1.9 79.601-20.4 143.3-55.4 191.2-27.6 37.8-69.4 69.1-125.3 93.8-25.7 11.3-36.8 41.7-24.8 67.101l35.9 75.8c11.601 24.399 40.501 35.2 65.301 24.399z">
          </path>
        </svg> See what others are saying</h2>
      <div class="block w-full h-0.5 max-w-lg mt-6 bg-purple-100 rounded-full"></div>
      <div class="items-center justify-center w-full mt-12 mb-4 lg:flex">
        <div class="flex flex-col items-start justify-start w-full h-auto mb-12 lg:w-1/3 lg:mb-0">
          <div class="flex items-center justify-center">
            <div class="w-16 h-16 mr-4 overflow-hidden bg-gray-200 rounded-full">
              <img
                src="https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1700&amp;q=80"
                class="object-cover w-full h-full">
            </div>
            <div class="flex flex-col items-start justify-center">
              <h4 class="font-bold text-gray-800">John Doe</h4>
              <p class="text-gray-600">CEO of Something</p>
            </div>
          </div>
          <blockquote class="mt-8 text-lg text-gray-500">"This is a no-brainer if you want to take your business to the
            next level. If you are looking for the ultimate toolset, this is it!"</blockquote>
        </div>
        <div
          class="flex flex-col items-start justify-start w-full h-auto px-0 mx-0 mb-12 border-l border-r border-transparent lg:w-1/3 lg:mb-0 lg:px-8 lg:mx-8 lg:border-gray-200">
          <div class="flex items-center justify-center">
            <div class="w-16 h-16 mr-4 overflow-hidden bg-gray-200 rounded-full">
              <img
                src="https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=2547&amp;q=80"
                class="object-cover w-full h-full">
            </div>
            <div class="flex flex-col items-start justify-center">
              <h4 class="font-bold text-gray-800">Jane Doe</h4>
              <p class="text-gray-600">CTO of Business</p>
            </div>
          </div>
          <blockquote class="mt-8 text-lg text-gray-500">"Thanks for creating this service. My life is so much easier.
            Thanks for making such a great product."</blockquote>
        </div>
        <div class="flex flex-col items-start justify-start w-full h-auto lg:w-1/3">
          <div class="flex items-center justify-center">
            <div class="w-16 h-16 mr-4 overflow-hidden bg-gray-200 rounded-full">
              <img
                src="https://images.unsplash.com/photo-1545167622-3a6ac756afa4?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1256&amp;q=80"
                class="object-cover w-full h-full">
            </div>
            <div class="flex flex-col items-start justify-center">
              <h4 class="font-bold text-gray-800">John Smith</h4>
              <p class="text-gray-600">Creator of Stuff</p>
            </div>
          </div>
          <blockquote class="mt-8 text-lg text-gray-500">"Packed with awesome content and exactly what I was looking
            for. I would highly recommend this to anyone."</blockquote>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section 4 -->
<section class="bg-white">
  <div class="max-w-screen-xl px-4 py-12 mx-auto space-y-8 overflow-hidden sm:px-6 lg:px-8">
    <nav class="flex flex-wrap justify-center -mx-5 -my-2">
      <% footers.each do |footer| %>
        <div class="px-5 py-2">
          <%= link_to footer[:title], footer[:link], class: "text-base leading-6 text-gray-500 hover:text-gray-900" %>
        </div>
      <% end %>
    </nav>
    <div class="flex justify-center mt-8 space-x-6">
      <% social_apps.each do |app| %>
        <%= link_to app[:link], class: "text-gray-400 hover:text-gray-500" do%>
          <span class="sr-only"><%= app[:title] %></span>
          <i class="<%= app[:icon] %> w-6 h-6"></i>
        <% end %>
      <% end %>
    </div>
    <p class="mt-8 text-base leading-6 text-center text-gray-400"> © 2021 SomeCompany, Inc. All rights reserved. </p>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="p-4 bg-white border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to "Licenser", root_path, class: "self-center text-xl font-semibold whitespace-nowrap dark:text-white" %>
    <button data-collapse-toggle="mobile-menu" type="button"
      class="inline-flex justify-center items-center ml-3 text-gray-400 rounded-lg md:hidden hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300 dark:text-gray-400 dark:hover:text-white dark:focus:ring-gray-500"
      aria-controls="mobile-menu-2" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
          clip-rule="evenodd"></path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <% nav_lists.each do |list| %>
          <% if list[:active] %>
            <li>
              <%= link_to list[:title], list[:path], data: { turbo_method: list[:method]}, class: "hover:text-primary block py-2 pr-4 pl-3 border-b md:border-0 border-gray-100 #{list[:unique_class]}" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Licenser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
    <%= any_login_here if defined?(AnyLogin) %>
  </body>
</html>

app/views/licenses/_comment.html.erb
<section>
  <div class="max-w-screen-xl px-4 py-8 mx-auto sm:px-6 lg:px-8">
    <h2 class="text-xl font-bold sm:text-2xl">Customer Reviews</h2>
    <div class="flex items-center mt-4">
      <p class="text-3xl font-medium"> 3.8 <span class="sr-only"> Average review score </span>
      </p>
      <div class="ml-4">
        <div class="flex -ml-1">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
            fill="currentColor">
            <path
              d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
            fill="currentColor">
            <path
              d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
            fill="currentColor">
            <path
              d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
            fill="currentColor">
            <path
              d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-gray-200" viewBox="0 0 20 20" fill="currentColor">
            <path
              d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
          </svg>
        </div>
        <p class="mt-0.5 text-xs text-gray-500">Based on 48 reviews</p>
      </div>
    </div>
    <div class="grid grid-cols-1 mt-8 lg:grid-cols-2 gap-x-16 gap-y-12">
      <% 4.times.each do |n| %>
        <blockquote>
          <header class="sm:items-center sm:flex">
            <div class="flex -ml-1">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
                fill="currentColor">
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
                fill="currentColor">
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
                fill="currentColor">
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-yellow-400" viewBox="0 0 20 20"
                fill="currentColor">
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-gray-200" viewBox="0 0 20 20"
                fill="currentColor">
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
            </div>
            <p class="mt-2 font-medium sm:ml-4 sm:mt-0">The best thing money can buy!</p>
          </header>
          <p class="mt-2 text-gray-700">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam possimus fuga
            dolor rerum dicta, ipsum laboriosam est totam iusto alias incidunt cum tempore aliquid aliquam error quisquam
            ipsam asperiores! Iste?</p>
          <footer class="mt-4">
            <p class="text-xs text-gray-500">John Doe - 12th January, 2024</p>
          </footer>
        </blockquote>
      <% end %>
    </div>
  </div>
</section>